- name: Installing oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/Users/{{ ansible_user }}/.oh-my-zsh"
    update: no
  register: ohmyzsh_result
  changed_when: "ohmyzsh_result.after|default('after') != ohmyzsh_result.before|default('before')"

- name: Setting default shell
  become: true
  shell: "chsh -s $(which zsh) {{ ansible_user }}"
  register: chsh_result
  changed_when: "'chsh: no changes made' not in chsh_result.stderr" 

- name: Install Powerline9k theme
  git:
    repo: "https://github.com/bhilburn/powerlevel9k.git"
    dest: "/Users/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel9k"
    update: no
  register: powerline9k_result
  changed_when: "powerline9k_result.after|default('after') != powerline9k_result.before|default('before')"

- name: Place .zshrc
  template:
    src: "zshrc.j2"
    dest: "/Users/{{ ansible_user }}/.zshrc"
    backup: yes

# Terminal
- name: Get default Terminal profile.
  shell: defaults read com.apple.Terminal 'Default Window Settings'
  register: default_theme
  changed_when: false

- name: Ensure custom Terminal profile is added.
  shell: "open '{{ role_path }}/files/{{ terminal_theme }}.terminal'"
  changed_when: false
  when: "terminal_theme != default_theme.stdout"
 
- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - "defaults write com.apple.Terminal 'Default Window Settings' -string '{{ terminal_theme }}'"
    - "defaults write com.apple.Terminal 'Startup Window Settings' -string '{{ terminal_theme }}'"
  changed_when: "terminal_theme != default_theme.stdout"

# iTerm
- name: Get iTerm prefs path.
  shell: defaults read com.googlecode.iterm2 'PrefsCustomFolder'
  changed_when: false
  register: default_iterm_prefs_path

- name: Set iTerm prefs path.
  shell: "{{ item }}"
  with_items:
    - "defaults write com.googlecode.iterm2 'PrefsCustomFolder' -string '{{ iterm_prefs_path }}'"
    - "defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true"
  changed_when: "iterm_prefs_path != default_iterm_prefs_path.stdout"
 