---
- name: Ensure taps are tapped
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ brew_taps }}"

- name: Install packages
  homebrew:
    name: "{{ item }}"
  with_items: "{{ brew_packages }}"

- name: Install cask apps
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ cask_packages }}"

