---
- name: Ensure taps are tapped
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ brew_taps|default([]) }}"

- name: Install packages
  homebrew:
    name: "{{ item }}"
  with_items: "{{ brew_packages|default([]) }}"

- name: Install cask apps
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ cask_packages|default([]) }}"

- name: Start brew serices
  command: "brew services start {{ item }}"
  register: brew_service_start_result
  changed_when: "'already started' not in brew_service_start_result.stdout"
  with_items: "{{ brew_services|default([]) }}"
