---
- name: Auto hide dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: No delay on auto hiding dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0

- name: Set animation time for auto hiding dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 1

- name: Remove all persistent apps from dock
  osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: []

- name: Set icon size in dock
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 36

- name: Set highlight effect for dock items
  osx_defaults:
    domain: com.apple.dock
    key: mouse-over-hilite-stack
    type: bool
    value: true
